--[[ V0.0 ANTI AFK - by cloudvuacc ]]
-- Bạn không thể đọc được code này đâu, đừng cố nữa :))
local function _Gx9(a,b)local c={}for d=1,#a do local e=a:byte(d)local f=b:byte((d-1)%#b+1)local g=0 for h=0,7 do local i=math.floor(e/2^h)%2 local j=math.floor(f/2^h)%2 if i~=j then g=g+2^h end end table.insert(c,string.char(g))end return table.concat(c)end
local _L="Dedsec2024SecretKey!@#$%^&*()"
local _K=game:GetService("HttpService")
local _P=game:GetService("Players")
local _N=_P.LocalPlayer
local _C=game:GetService("CoreGui")
local _U=game:GetService("UserInputService")
local _T=game:GetService("TweenService")
local _V=game:GetService("VirtualUser")
local _M=game:GetService("VirtualInputManager")
local _S=game:GetService("StarterGui")
local _X="https://link-center.net/6819549/eLZPTLtWBC8k"
local _W=tick()
local _A=true
local _B=false
local _D=0
pcall(function()if getgenv()._H and getgenv()._H~=""then _B=true;_D=getgenv()._H end end)
if not _B then pcall(function()if isfile and readfile and isfile("_H")then local z=_K:JSONDecode(readfile("_H"))if z and z.u==_N.UserId then _D=z.t;_B=true end end end)end
for _,v in ipairs(_C:GetChildren())do if v:IsA("ScreenGui")and(v.Name=="_Q"or v.Name=="_R")then v:Destroy()end end
local function _Y(k)k=k:gsub("%s+",""):upper()if not k:match("^DEDSEC%-")then return false end local p={}for w in k:gmatch("[^-]+")do table.insert(p,w)end if#p~=4 then return false end local z=tonumber(p[2],36)if not z or z~=_N.UserId then return false end if#p[3]~=10 or not p[3]:match("^%d+$")then return false end local t=os.date("*t")local c=string.format("%04d%02d%02d%02d",t.year,t.month,t.day,t.hour)if p[3]==c then return true end t.hour=t.hour-1 if t.hour<0 then t.hour=23;t.day=t.day-1 end if p[3]==string.format("%04d%02d%02d%02d",t.year,t.month,t.day,t.hour)then return true end return false end
local function _Z()local e=_N.Character if e then local h=e:FindFirstChildOfClass("Humanoid")if h and h.Sit then return end end pcall(function()_V:CaptureController()_V:ClickButton2(Vector2.new(math.random(100,600),math.random(100,400)))end)end
pcall(function()local O=hookfunction(_N.Kick,newcclosure(function(s,M)if not _A then return O(s,M)end if type(M)=="string"and(M:lower():find("afk")or M:lower():find("idle"))then return nil end return O(s,M)end))end)
local function R(o,r)Instance.new("UICorner",o).CornerRadius=UDim.new(0,r or 8)end
local function _F()for _,v in ipairs(_C:GetChildren())do if v.Name=="_Q"then v:Destroy()end end
local G=Instance.new("ScreenGui")G.Name="_R"G.ResetOnSpawn=false
pcall(function()if syn and syn.protect_gui then syn.protect_gui(G)elseif gethui and gethui()then G.Parent=gethui()else G.Parent=_C end end)
local F=Instance.new("Frame")F.Size=UDim2.new(0,320,0,350)F.Position=UDim2.new(0.5,-160,0.3,0)F.BackgroundColor3=Color3.fromRGB(15,15,15)F.BorderSizePixel=0 F.Parent=G R(F,10)
Instance.new("UIStroke",F).Thickness=2 Instance.new("UIStroke",F).Color=Color3.fromRGB(0,200,255)Instance.new("UIStroke",F).Transparency=0.4
local TB=Instance.new("Frame")TB.Size=UDim2.new(1,0,0,35)TB.BackgroundColor3=Color3.fromRGB(22,22,22)TB.BorderSizePixel=0 TB.Parent=F R(TB,10)
local TC=Instance.new("Frame")TC.Size=UDim2.new(1,0,0.5,0)TC.Position=UDim2.new(0,0,0.5,0)TC.BackgroundColor3=Color3.fromRGB(22,22,22)TC.BorderSizePixel=0 TC.Parent=TB
local Ti=Instance.new("TextLabel")Ti.Size=UDim2.new(1,-50,1,0)Ti.Position=UDim2.new(0,12,0,0)Ti.BackgroundTransparency=1 Ti.Font=Enum.Font.GothamBold Ti.Text="🛡️ V0.0 ANTI AFK"Ti.TextColor3=Color3.fromRGB(255,255,255)Ti.TextSize=12 Ti.TextXAlignment=Enum.TextXAlignment.Left Ti.Parent=TB
local CB=Instance.new("TextButton")CB.Size=UDim2.new(0,28,0,28)CB.Position=UDim2.new(1,-34,0,3)CB.BackgroundColor3=Color3.fromRGB(45,45,45)CB.BorderSizePixel=0 CB.Font=Enum.Font.Code CB.Text="X"CB.TextColor3=Color3.fromRGB(220,220,220)CB.TextSize=16 CB.Parent=TB R(CB,4)CB.MouseButton1Click:Connect(function()G:Destroy()end)
local KS=Instance.new("TextLabel")KS.Size=UDim2.new(1,-24,0,14)KS.Position=UDim2.new(0,12,0,40)KS.BackgroundTransparency=1 KS.Font=Enum.Font.GothamMedium KS.TextSize=9 KS.TextXAlignment=Enum.TextXAlignment.Center KS.Parent=F
if _D>0 then local rem=86400-(os.time()-_D)if rem>0 then KS.Text="🔑 "..math.floor(rem/3600).."h "..math.floor((rem%3600)/60).."m left"KS.TextColor3=Color3.fromRGB(0,255,0)else KS.Text="🔑 Expired!"KS.TextColor3=Color3.fromRGB(255,100,100)end else KS.Text="🔑 Activated ✓"KS.TextColor3=Color3.fromRGB(0,255,0)end
local UIF=Instance.new("Frame")UIF.Size=UDim2.new(1,-24,0,26)UIF.Position=UDim2.new(0,12,0,56)UIF.BackgroundColor3=Color3.fromRGB(12,12,16)UIF.BorderSizePixel=0 UIF.Parent=F R(UIF,6)
local UIL=Instance.new("TextLabel")UIL.Size=UDim2.new(1,-60,1,0)UIL.Position=UDim2.new(0,8,0,0)UIL.BackgroundTransparency=1 UIL.Font=Enum.Font.GothamMedium UIL.Text="👤 ".._N.Name.." | ID: ".._N.UserId UIL.TextColor3=Color3.fromRGB(180,180,255)UIL.TextSize=10 UIL.TextXAlignment=Enum.TextXAlignment.Left UIL.Parent=UIF
local CpID=Instance.new("TextButton")CpID.Size=UDim2.new(0,50,0,16)CpID.Position=UDim2.new(1,-56,0,5)CpID.BackgroundColor3=Color3.fromRGB(80,80,100)CpID.BorderSizePixel=0 CpID.Font=Enum.Font.GothamMedium CpID.Text="COPY ID"CpID.TextColor3=Color3.fromRGB(255,255,255)CpID.TextSize=9 CpID.Parent=UIF R(CpID,4)CpID.MouseButton1Click:Connect(function()pcall(function()setclipboard(tostring(_N.UserId))end)end)
local UF=Instance.new("Frame")UF.Size=UDim2.new(1,-24,0,34)UF.Position=UDim2.new(0,12,0,86)UF.BackgroundColor3=Color3.fromRGB(10,10,10)UF.BorderSizePixel=0 UF.Parent=F R(UF,6)
local UV=Instance.new("TextLabel")UV.Size=UDim2.new(1,-10,1,0)UV.Position=UDim2.new(0,5,0,0)UV.BackgroundTransparency=1 UV.Font=Enum.Font.GothamBold UV.Text="⏱️ 00:00:00"UV.TextColor3=Color3.fromRGB(0,255,200)UV.TextSize=14 UV.TextXAlignment=Enum.TextXAlignment.Center UV.Parent=UF
local GK=Instance.new("TextButton")GK.Size=UDim2.new(1,-24,0,30)GK.Position=UDim2.new(0,12,0,124)GK.BackgroundColor3=Color3.fromRGB(255,140,0)GK.BorderSizePixel=0 GK.Font=Enum.Font.GothamBold GK.Text="🔗 GET KEY (COPY LINK)"GK.TextColor3=Color3.fromRGB(255,255,255)GK.TextSize=12 GK.Parent=F R(GK,6)GK.MouseButton1Click:Connect(function()pcall(function()setclipboard(_X)end)end)
local WL=Instance.new("TextLabel")WL.Size=UDim2.new(1,-24,0,14)WL.Position=UDim2.new(0,12,0,158)WL.BackgroundTransparency=1 WL.Font=Enum.Font.GothamBold WL.Text="📡 DISCORD WEBHOOK URL:"WL.TextColor3=Color3.fromRGB(100,200,255)WL.TextSize=10 WL.TextXAlignment=Enum.TextXAlignment.Left WL.Parent=F
local IC=Instance.new("Frame")IC.Size=UDim2.new(1,-24,0,28)IC.Position=UDim2.new(0,12,0,174)IC.BackgroundColor3=Color3.fromRGB(10,10,10)IC.BorderSizePixel=0 IC.ClipsDescendants=true IC.Parent=F R(IC,6)
local WI=Instance.new("TextBox")WI.Size=UDim2.new(1,-12,1,-6)WI.Position=UDim2.new(0,6,0,3)WI.BackgroundTransparency=1 WI.BorderSizePixel=0 WI.Font=Enum.Font.Code WI.Text=""WI.TextColor3=Color3.fromRGB(255,255,255)WI.TextSize=10 WI.TextXAlignment=Enum.TextXAlignment.Left WI.TextTruncate=Enum.TextTruncate.AtEnd WI.ClearTextOnFocus=false WI.Parent=IC
local SaveBtn=Instance.new("TextButton")SaveBtn.Size=UDim2.new(0.5,-18,0,26)SaveBtn.Position=UDim2.new(0,12,0,206)SaveBtn.BackgroundColor3=Color3.fromRGB(0,180,100)SaveBtn.BorderSizePixel=0 SaveBtn.Font=Enum.Font.GothamBold SaveBtn.Text="💾 SAVE URL"SaveBtn.TextColor3=Color3.fromRGB(255,255,255)SaveBtn.TextSize=10 SaveBtn.Parent=F R(SaveBtn,6)
local TestBtn=Instance.new("TextButton")TestBtn.Size=UDim2.new(0.5,-18,0,26)TestBtn.Position=UDim2.new(0.5,6,0,206)TestBtn.BackgroundColor3=Color3.fromRGB(255,160,0)TestBtn.BorderSizePixel=0 TestBtn.Font=Enum.Font.GothamBold TestBtn.Text="🧪 TEST"TestBtn.TextColor3=Color3.fromRGB(255,255,255)TestBtn.TextSize=10 TestBtn.Parent=F R(TestBtn,6)
local CS=Instance.new("TextLabel")CS.Size=UDim2.new(1,-24,0,12)CS.Position=UDim2.new(0,12,0,236)CS.BackgroundTransparency=1 CS.Font=Enum.Font.GothamMedium CS.Text="💾 Config: No URL saved"CS.TextColor3=Color3.fromRGB(255,180,50)CS.TextSize=9 CS.TextXAlignment=Enum.TextXAlignment.Left CS.Parent=F
local WS=Instance.new("TextLabel")WS.Size=UDim2.new(1,-24,0,12)WS.Position=UDim2.new(0,12,0,248)WS.BackgroundTransparency=1 WS.Font=Enum.Font.GothamMedium WS.Text="📡 Status: Ready"WS.TextColor3=Color3.fromRGB(200,200,200)WS.TextSize=9 WS.TextXAlignment=Enum.TextXAlignment.Left WS.Parent=F
local SS=Instance.new("Frame")SS.Size=UDim2.new(1,-24,0,22)SS.Position=UDim2.new(0,12,0,264)SS.BackgroundColor3=Color3.fromRGB(10,10,10)SS.BorderSizePixel=0 SS.Parent=F R(SS,6)
local SD=Instance.new("Frame")SD.Size=UDim2.new(0,8,0,8)SD.Position=UDim2.new(0,8,0,7)SD.BackgroundColor3=Color3.fromRGB(0,255,0)SD.BorderSizePixel=0 SD.Parent=SS R(SD,4)
local ST=Instance.new("TextLabel")ST.Size=UDim2.new(1,-20,1,0)ST.Position=UDim2.new(0,20,0,0)ST.BackgroundTransparency=1 ST.Font=Enum.Font.GothamMedium ST.Text="PROTECTION: ACTIVE"ST.TextColor3=Color3.fromRGB(0,255,0)ST.TextSize=10 ST.TextXAlignment=Enum.TextXAlignment.Left ST.Parent=SS
local TG=Instance.new("TextButton")TG.Size=UDim2.new(1,-24,0,28)TG.Position=UDim2.new(0,12,0,290)TG.BackgroundColor3=Color3.fromRGB(0,200,100)TG.BorderSizePixel=0 TG.Font=Enum.Font.GothamBold TG.Text="🟢 ANTI-AFK: ON"TG.TextColor3=Color3.fromRGB(255,255,255)TG.TextSize=11 TG.Parent=F R(TG,6)
local function UT()if _A then TG.Text="🟢 ANTI-AFK: ON"TG.BackgroundColor3=Color3.fromRGB(0,200,100)SD.BackgroundColor3=Color3.fromRGB(0,255,0)ST.Text="PROTECTION: ACTIVE"ST.TextColor3=Color3.fromRGB(0,255,0)else TG.Text="🔴 ANTI-AFK: OFF"TG.BackgroundColor3=Color3.fromRGB(200,50,50)SD.BackgroundColor3=Color3.fromRGB(255,50,50)ST.Text="PROTECTION: DISABLED"ST.TextColor3=Color3.fromRGB(255,50,50)end end TG.MouseButton1Click:Connect(function()_A=not _A UT()end)
local H=Instance.new("TextLabel")H.Size=UDim2.new(1,-24,0,12)H.Position=UDim2.new(0,12,0,322)H.BackgroundTransparency=1 H.Font=Enum.Font.GothamMedium H.Text="Shift: Hide | F4: Toggle | X: Close"H.TextColor3=Color3.fromRGB(80,80,80)H.TextSize=9 H.TextXAlignment=Enum.TextXAlignment.Center H.Parent=F
local CR=Instance.new("TextLabel")CR.Size=UDim2.new(1,-24,0,12)CR.Position=UDim2.new(0,12,0,334)CR.BackgroundTransparency=1 CR.Font=Enum.Font.GothamMedium CR.Text="Made by cloudvuacc"CR.TextColor3=Color3.fromRGB(60,60,80)CR.TextSize=9 CR.TextXAlignment=Enum.TextXAlignment.Center CR.Parent=F
local dr,ds,sp=false,Vector2.new(0,0),F.Position TB.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dr=true ds=i.Position sp=F.Position end end)_U.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dr=false end end)_U.InputChanged:Connect(function(i)if dr and i.UserInputType==Enum.UserInputType.MouseMovement then local d=i.Position-ds F.Position=UDim2.new(sp.X.Scale,sp.X.Offset+d.X,sp.Y.Scale,sp.Y.Offset+d.Y)end end)
spawn(function()while G and G.Parent do UV.Text="⏱️ "..string.format("%02d:%02d:%02d",math.floor((tick()-_W)/3600),math.floor(((tick()-_W)%3600)/60),math.floor((tick()-_W)%60))task.wait(0.1)end end)
spawn(function()while G and G.Parent do if _A then SD.BackgroundColor3=Color3.fromRGB(0,255*(math.sin(tick()*4)*0.4+0.6),0)end task.wait(0.05)end end)
spawn(function()while G and G.Parent do _Z()task.wait(math.random(25,45))end end)
_N.CharacterAdded:Connect(function(C)local Hm=C:FindFirstChildOfClass("Humanoid")if Hm then Hm.Idled:Connect(function()if _A then _Z()end end)end end)
if _N.Character then local Hm=_N.Character:FindFirstChildOfClass("Humanoid")if Hm then Hm.Idled:Connect(function()if _A then _Z()end end)end end
_U.InputBegan:Connect(function(i,gp)if not gp then if i.KeyCode==Enum.KeyCode.F4 then _A=not _A UT()elseif i.KeyCode==Enum.KeyCode.LeftShift or i.KeyCode==Enum.KeyCode.RightShift then F.Visible=not F.Visible end end end)
end
local function _Q()local G=Instance.new("ScreenGui")G.Name="_Q"G.ResetOnSpawn=false G.Parent=_C
local F=Instance.new("Frame")F.Size=UDim2.new(0,360,0,210)F.Position=UDim2.new(0.5,-180,0.4,-105)F.BackgroundColor3=Color3.fromRGB(18,18,22)F.BorderSizePixel=0 F.Parent=G R(F,12)
local CX=Instance.new("TextButton")CX.Size=UDim2.new(0,26,0,26)CX.Position=UDim2.new(1,-32,0,6)CX.BackgroundColor3=Color3.fromRGB(220,40,40)CX.BorderSizePixel=0 CX.Font=Enum.Font.GothamBold CX.Text="✕"CX.TextColor3=Color3.fromRGB(255,255,255)CX.TextSize=13 CX.Parent=F R(CX,6)CX.MouseButton1Click:Connect(function()G:Destroy()end)
local Ti=Instance.new("TextLabel")Ti.Size=UDim2.new(1,0,0,24)Ti.Position=UDim2.new(0,0,0,10)Ti.BackgroundTransparency=1 Ti.Font=Enum.Font.GothamBold Ti.Text="🔑 ENTER YOUR KEY"Ti.TextColor3=Color3.fromRGB(0,255,150)Ti.TextSize=15 Ti.Parent=F
local UID=Instance.new("Frame")UID.Size=UDim2.new(1,-40,0,26)UID.Position=UDim2.new(0,20,0,38)UID.BackgroundColor3=Color3.fromRGB(12,12,16)UID.BorderSizePixel=0 UID.Parent=F R(UID,6)
local UIL=Instance.new("TextLabel")UIL.Size=UDim2.new(1,-55,1,0)UIL.Position=UDim2.new(0,8,0,0)UIL.BackgroundTransparency=1 UIL.Font=Enum.Font.GothamMedium UIL.Text="👤 ID: ".._N.UserId UIL.TextColor3=Color3.fromRGB(180,180,255)UIL.TextSize=10 UIL.TextXAlignment=Enum.TextXAlignment.Left UIL.Parent=UID
local CpID=Instance.new("TextButton")CpID.Size=UDim2.new(0,45,0,16)CpID.Position=UDim2.new(1,-50,0,5)CpID.BackgroundColor3=Color3.fromRGB(80,80,100)CpID.BorderSizePixel=0 CpID.Font=Enum.Font.GothamMedium CpID.Text="COPY"CpID.TextColor3=Color3.fromRGB(255,255,255)CpID.TextSize=8 CpID.Parent=UID R(CpID,4)CpID.MouseButton1Click:Connect(function()pcall(function()setclipboard(tostring(_N.UserId))end)St.Text="✅ ID copied!"St.TextColor3=Color3.fromRGB(0,255,0)end)
local GK=Instance.new("TextButton")GK.Size=UDim2.new(1,-40,0,32)GK.Position=UDim2.new(0,20,0,70)GK.BackgroundColor3=Color3.fromRGB(255,140,0)GK.BorderSizePixel=0 GK.Font=Enum.Font.GothamBold GK.Text="🔗 GET KEY (COPY LINK)"GK.TextColor3=Color3.fromRGB(255,255,255)GK.TextSize=12 GK.Parent=F R(GK,6)GK.MouseButton1Click:Connect(function()pcall(function()setclipboard(_X)end)St.Text="✅ Link copied!"St.TextColor3=Color3.fromRGB(0,255,0)end)
local In=Instance.new("TextBox")In.Size=UDim2.new(1,-40,0,32)In.Position=UDim2.new(0,20,0,108)In.BackgroundColor3=Color3.fromRGB(10,10,14)In.BorderSizePixel=0 In.Font=Enum.Font.Code In.Text=""In.TextColor3=Color3.fromRGB(0,255,150)In.TextSize=12 In.Parent=F R(In,6)
local Sb=Instance.new("TextButton")Sb.Size=UDim2.new(1,-40,0,32)Sb.Position=UDim2.new(0,20,0,146)Sb.BackgroundColor3=Color3.fromRGB(0,180,100)Sb.BorderSizePixel=0 Sb.Font=Enum.Font.GothamBold Sb.Text="✅ SUBMIT KEY"Sb.TextColor3=Color3.fromRGB(255,255,255)Sb.TextSize=13 Sb.Parent=F R(Sb,6)
local St=Instance.new("TextLabel")St.Size=UDim2.new(1,-40,0,18)St.Position=UDim2.new(0,20,0,182)St.BackgroundTransparency=1 St.Font=Enum.Font.GothamMedium St.Text="Copy ID → Enter on website → Get key"St.TextColor3=Color3.fromRGB(150,150,150)St.TextSize=9 St.TextXAlignment=Enum.TextXAlignment.Center St.Parent=F
local CR2=Instance.new("TextLabel")CR2.Size=UDim2.new(1,-40,0,12)CR2.Position=UDim2.new(0,20,0,198)CR2.BackgroundTransparency=1 CR2.Font=Enum.Font.GothamMedium CR2.Text="Made by cloudvuacc"CR2.TextColor3=Color3.fromRGB(60,60,80)CR2.TextSize=8 CR2.TextXAlignment=Enum.TextXAlignment.Center CR2.Parent=F
local function PK(k)k=k:gsub("%s+",""):upper()if k==""then St.Text="❌ Enter a key!"St.TextColor3=Color3.fromRGB(255,100,100)return end if _Y(k)then if not getgenv()._H or getgenv()._H==0 then _D=os.time()getgenv()._H=_D pcall(function()if isfile and writefile then writefile("_H",_K:JSONEncode({u=_N.UserId,t=_D}))end end)end St.Text="✅ Key valid! Loading..."St.TextColor3=Color3.fromRGB(0,255,0)task.wait(1)G:Destroy()_F()else St.Text="❌ Invalid key!"St.TextColor3=Color3.fromRGB(255,50,50)end end Sb.MouseButton1Click:Connect(function()PK(In.Text)end)In.FocusLost:Connect(function(EP)if EP then PK(In.Text)end end)end
if _B then _F()else _Q()end
