--[[ V0.0 ANTI AFK - cloudvuacc ]]
local a=game local b=a:GetService local c=b(a,"HttpService")local d=b(a,"Players")local e=d.LocalPlayer local f=b(a,"CoreGui")local g=b(a,"UserInputService")local h=b(a,"TweenService")local i=b(a,"VirtualUser")local j=b(a,"StarterGui")local k="https://link-center.net/6819549/eLZPTLtWBC8k"local l=tick()local m=true local n=""local o=false local p=0 local q=0 local r=300 local s=e.Name local t="???"pcall(function()t=b(a,"MarketplaceService"):GetProductInfo(a.PlaceId).Name end)
pcall(function()if getgenv()._k and getgenv()._k>0 then o=true;p=getgenv()._k end end)if not o then pcall(function()if shared._k and shared._k>0 then o=true;p=shared._k end end)end if not o then pcall(function()if _G._k and _G._k>0 then o=true;p=_G._k end end)end if not o then pcall(function()if isfile and readfile and isfile("_k.cfg")then local z=c:JSONDecode(readfile("_k.cfg"))if z and z.u==e.UserId and z.t>0 then if os.time()-z.t<86400 then p=z.t;o=true end end end end)end
pcall(function()if getgenv()._w and getgenv()._w~=""then n=getgenv()._w end end)if n==""then pcall(function()if shared._w and shared._w~=""then n=shared._w end end)end if n==""then pcall(function()if _G._w and _G._w~=""then n=_G._w end end)end if n==""then pcall(function()if isfile and readfile and isfile("_w.cfg")then local z=c:JSONDecode(readfile("_w.cfg"))if z and z.u and z.u~=""then n=z.u end end end)end
for _,v in ipairs(f:GetChildren())do if v:IsA("ScreenGui")then v:Destroy()end end
local function u(k)k=k:gsub("%s+",""):upper()if not k:match("^DEDSEC%-")then return false end local p={}for w in k:gmatch("[^-]+")do p[#p+1]=w end if#p~=4 then return false end local z=tonumber(p[2],36)if not z or z~=e.UserId then return false end if#p[3]~=10 or not p[3]:match("^%d+$")then return false end local t=os.date("*t")local c=string.format("%04d%02d%02d%02d",t.year,t.month,t.day,t.hour)if p[3]==c then return true end t.hour=t.hour-1 if t.hour<0 then t.hour=23;t.day=t.day-1 end if p[3]==string.format("%04d%02d%02d%02d",t.year,t.month,t.day,t.hour)then return true end return false end
local function v(u)n=u;getgenv()._w=u;shared._w=u;_G._w=u;pcall(function()if isfile and writefile then writefile("_w.cfg",c:JSONEncode({u=u,n=s,t=os.time()}))end end)end
local function w()getgenv()._k=p;shared._k=p;_G._k=p;pcall(function()if isfile and writefile then writefile("_k.cfg",c:JSONEncode({u=e.UserId,t=p,n=s}))end end)end
local function x(s)return string.format("%02d:%02d:%02d",math.floor(s/3600),math.floor((s%3600)/60),math.floor(s%60))end
local function y(T,D,C)if n==""then return false end local ok=false pcall(function()local P={["content"]="",["embeds"]={{["title"]=T,["description"]=D,["color"]=C or 65280,["footer"]={["text"]="V0.0 | "..s}}}}local B=c:JSONEncode(P)local R=request or http_request or syn.request if R then R({Url=n,Method="POST",Headers={["Content-Type"]="application/json"},Body=B})ok=true end end)return ok end
local function z()if not m then return end local ch=e.Character if ch then local hm=ch:FindFirstChildOfClass("Humanoid")if hm and hm.Sit then return end end pcall(function()i:CaptureController()i:ClickButton2(Vector2.new(math.random(100,600),math.random(100,400)))end)end
pcall(function()local O=hookfunction(e.Kick,newcclosure(function(s,M)if not m then return O(s,M)end if type(M)=="string"and(M:lower():find("afk")or M:lower():find("idle"))then return nil end return O(s,M)end))end)
local function A(o,r)Instance.new("UICorner",o).CornerRadius=UDim.new(0,r or 8)end

-- MAIN MENU
local function B()
for _,v in ipairs(f:GetChildren())do if v.Name=="_q"then v:Destroy()end end
local G=Instance.new("ScreenGui")G.Name="_r"G.ResetOnSpawn=false
pcall(function()if syn and syn.protect_gui then syn.protect_gui(G)elseif gethui and gethui()then G.Parent=gethui()else G.Parent=f end end)
local F=Instance.new("Frame")F.Size=UDim2.new(0,320,0,310)F.Position=UDim2.new(0.5,-160,0.3,0)F.BackgroundColor3=Color3.fromRGB(15,15,15)F.BorderSizePixel=0 F.Parent=G A(F,10)
local TB=Instance.new("Frame")TB.Size=UDim2.new(1,0,0,35)TB.BackgroundColor3=Color3.fromRGB(22,22,22)TB.BorderSizePixel=0 TB.Parent=F A(TB,10)
local TC=Instance.new("Frame")TC.Size=UDim2.new(1,0,0.5,0)TC.Position=UDim2.new(0,0,0.5,0)TC.BackgroundColor3=Color3.fromRGB(22,22,22)TC.BorderSizePixel=0 TC.Parent=TB
local Ti=Instance.new("TextLabel")Ti.Size=UDim2.new(1,-50,1,0)Ti.Position=UDim2.new(0,12,0,0)Ti.BackgroundTransparency=1 Ti.Font=Enum.Font.GothamBold Ti.Text="🛡️ V0.0 ANTI AFK"Ti.TextColor3=Color3.fromRGB(255,255,255)Ti.TextSize=12 Ti.TextXAlignment=Enum.TextXAlignment.Left Ti.Parent=TB
local CB=Instance.new("TextButton")CB.Size=UDim2.new(0,28,0,28)CB.Position=UDim2.new(1,-34,0,3)CB.BackgroundColor3=Color3.fromRGB(45,45,45)CB.BorderSizePixel=0 CB.Font=Enum.Font.Code CB.Text="X"CB.TextColor3=Color3.fromRGB(220,220,220)CB.TextSize=16 CB.Parent=TB A(CB,4)CB.MouseButton1Click:Connect(function()G:Destroy()end)
local KS=Instance.new("TextLabel")KS.Size=UDim2.new(1,-24,0,14)KS.Position=UDim2.new(0,12,0,40)KS.BackgroundTransparency=1 KS.Font=Enum.Font.GothamMedium KS.TextSize=9 KS.TextXAlignment=Enum.TextXAlignment.Center KS.Parent=F
if p>0 then local rem=86400-(os.time()-p)if rem>0 then KS.Text="🔑 "..math.floor(rem/3600).."h "..math.floor((rem%3600)/60).."m left"KS.TextColor3=Color3.fromRGB(0,255,0)else KS.Text="🔑 Expired!"KS.TextColor3=Color3.fromRGB(255,100,100)end else KS.Text="🔑 Activated ✓"KS.TextColor3=Color3.fromRGB(0,255,0)end
local UIF=Instance.new("Frame")UIF.Size=UDim2.new(1,-24,0,26)UIF.Position=UDim2.new(0,12,0,56)UIF.BackgroundColor3=Color3.fromRGB(12,12,16)UIF.BorderSizePixel=0 UIF.Parent=F A(UIF,6)
local UIL=Instance.new("TextLabel")UIL.Size=UDim2.new(1,-60,1,0)UIL.Position=UDim2.new(0,8,0,0)UIL.BackgroundTransparency=1 UIL.Font=Enum.Font.GothamMedium UIL.Text="👤 "..e.Name.." | ID: "..e.UserId UIL.TextColor3=Color3.fromRGB(180,180,255)UIL.TextSize=10 UIL.TextXAlignment=Enum.TextXAlignment.Left UIL.Parent=UIF
local CpID=Instance.new("TextButton")CpID.Size=UDim2.new(0,50,0,16)CpID.Position=UDim2.new(1,-56,0,5)CpID.BackgroundColor3=Color3.fromRGB(80,80,100)CpID.BorderSizePixel=0 CpID.Font=Enum.Font.GothamMedium CpID.Text="COPY ID"CpID.TextColor3=Color3.fromRGB(255,255,255)CpID.TextSize=9 CpID.Parent=UIF A(CpID,4)CpID.MouseButton1Click:Connect(function()pcall(function()setclipboard(tostring(e.UserId))end)end)
local UF=Instance.new("Frame")UF.Size=UDim2.new(1,-24,0,34)UF.Position=UDim2.new(0,12,0,86)UF.BackgroundColor3=Color3.fromRGB(10,10,10)UF.BorderSizePixel=0 UF.Parent=F A(UF,6)
local UV=Instance.new("TextLabel")UV.Size=UDim2.new(1,-10,1,0)UV.Position=UDim2.new(0,5,0,0)UV.BackgroundTransparency=1 UV.Font=Enum.Font.GothamBold UV.Text="⏱️ 00:00:00"UV.TextColor3=Color3.fromRGB(0,255,200)UV.TextSize=14 UV.TextXAlignment=Enum.TextXAlignment.Center UV.Parent=UF
local WL=Instance.new("TextLabel")WL.Size=UDim2.new(1,-24,0,14)WL.Position=UDim2.new(0,12,0,124)WL.BackgroundTransparency=1 WL.Font=Enum.Font.GothamBold WL.Text="📡 WEBHOOK URL:"WL.TextColor3=Color3.fromRGB(100,200,255)WL.TextSize=10 WL.TextXAlignment=Enum.TextXAlignment.Left WL.Parent=F
local IC=Instance.new("Frame")IC.Size=UDim2.new(1,-24,0,28)IC.Position=UDim2.new(0,12,0,140)IC.BackgroundColor3=Color3.fromRGB(10,10,10)IC.BorderSizePixel=0 IC.ClipsDescendants=true IC.Parent=F A(IC,6)
local WI=Instance.new("TextBox")WI.Size=UDim2.new(1,-12,1,-6)WI.Position=UDim2.new(0,6,0,3)WI.BackgroundTransparency=1 WI.BorderSizePixel=0 WI.Font=Enum.Font.Code WI.Text=n or""WI.TextColor3=Color3.fromRGB(255,255,255)WI.TextSize=10 WI.TextXAlignment=Enum.TextXAlignment.Left WI.TextTruncate=Enum.TextTruncate.AtEnd WI.ClearTextOnFocus=false WI.Parent=IC
local SaveBtn=Instance.new("TextButton")SaveBtn.Size=UDim2.new(0.5,-18,0,26)SaveBtn.Position=UDim2.new(0,12,0,172)SaveBtn.BackgroundColor3=Color3.fromRGB(0,180,100)SaveBtn.BorderSizePixel=0 SaveBtn.Font=Enum.Font.GothamBold SaveBtn.Text="💾 SAVE"SaveBtn.TextColor3=Color3.fromRGB(255,255,255)SaveBtn.TextSize=10 SaveBtn.Parent=F A(SaveBtn,6)
SaveBtn.MouseButton1Click:Connect(function()v(WI.Text)if n~=""then CS.Text="💾 Config: Saved ✓"CS.TextColor3=Color3.fromRGB(0,255,100)WS.Text="📡 Ready"WS.TextColor3=Color3.fromRGB(0,255,100)else WS.Text="📡 Invalid URL!"WS.TextColor3=Color3.fromRGB(255,50,50)end end)
local TestBtn=Instance.new("TextButton")TestBtn.Size=UDim2.new(0.5,-18,0,26)TestBtn.Position=UDim2.new(0.5,6,0,172)TestBtn.BackgroundColor3=Color3.fromRGB(255,160,0)TestBtn.BorderSizePixel=0 TestBtn.Font=Enum.Font.GothamBold TestBtn.Text="🧪 TEST"TestBtn.TextColor3=Color3.fromRGB(255,255,255)TestBtn.TextSize=10 TestBtn.Parent=F A(TestBtn,6)
TestBtn.MouseButton1Click:Connect(function()if WI.Text~=""then v(WI.Text)end if n~=""then local ok=y("🧪 Test","✅ Webhook active!\n**"..s.."**",3447003)if ok then WS.Text="📡 Test Sent ✓"WS.TextColor3=Color3.fromRGB(0,255,100)else WS.Text="📡 Failed!"WS.TextColor3=Color3.fromRGB(255,50,50)end else WS.Text="📡 No URL!"WS.TextColor3=Color3.fromRGB(255,50,50)end end)
local function C(L)if n~=""then L.Text="💾 Config: Saved ✓"L.TextColor3=Color3.fromRGB(0,255,100)else L.Text="💾 Config: No URL"L.TextColor3=Color3.fromRGB(255,180,50)end end
local CS=Instance.new("TextLabel")CS.Size=UDim2.new(1,-24,0,12)CS.Position=UDim2.new(0,12,0,202)CS.BackgroundTransparency=1 CS.Font=Enum.Font.GothamMedium CS.TextSize=9 CS.TextXAlignment=Enum.TextXAlignment.Left CS.Parent=F C(CS)
local WS=Instance.new("TextLabel")WS.Size=UDim2.new(1,-24,0,12)WS.Position=UDim2.new(0,12,0,214)WS.BackgroundTransparency=1 WS.Font=Enum.Font.GothamMedium WS.Text="📡 Ready"WS.TextColor3=Color3.fromRGB(200,200,200)WS.TextSize=9 WS.TextXAlignment=Enum.TextXAlignment.Left WS.Parent=F
local SS=Instance.new("Frame")SS.Size=UDim2.new(1,-24,0,22)SS.Position=UDim2.new(0,12,0,230)SS.BackgroundColor3=Color3.fromRGB(10,10,10)SS.BorderSizePixel=0 SS.Parent=F A(SS,6)
local SD=Instance.new("Frame")SD.Size=UDim2.new(0,8,0,8)SD.Position=UDim2.new(0,8,0,7)SD.BackgroundColor3=Color3.fromRGB(0,255,0)SD.BorderSizePixel=0 SD.Parent=SS A(SD,4)
local ST=Instance.new("TextLabel")ST.Size=UDim2.new(1,-20,1,0)ST.Position=UDim2.new(0,20,0,0)ST.BackgroundTransparency=1 ST.Font=Enum.Font.GothamMedium ST.Text="PROTECTION: ACTIVE"ST.TextColor3=Color3.fromRGB(0,255,0)ST.TextSize=10 ST.TextXAlignment=Enum.TextXAlignment.Left ST.Parent=SS
local TG=Instance.new("TextButton")TG.Size=UDim2.new(1,-24,0,28)TG.Position=UDim2.new(0,12,0,256)TG.BackgroundColor3=Color3.fromRGB(0,200,100)TG.BorderSizePixel=0 TG.Font=Enum.Font.GothamBold TG.Text="🟢 ANTI-AFK: ON"TG.TextColor3=Color3.fromRGB(255,255,255)TG.TextSize=11 TG.Parent=F A(TG,6)
local function UT()if m then TG.Text="🟢 ANTI-AFK: ON"TG.BackgroundColor3=Color3.fromRGB(0,200,100)SD.BackgroundColor3=Color3.fromRGB(0,255,0)ST.Text="PROTECTION: ACTIVE"ST.TextColor3=Color3.fromRGB(0,255,0)else TG.Text="🔴 ANTI-AFK: OFF"TG.BackgroundColor3=Color3.fromRGB(200,50,50)SD.BackgroundColor3=Color3.fromRGB(255,50,50)ST.Text="PROTECTION: DISABLED"ST.TextColor3=Color3.fromRGB(255,50,50)end end TG.MouseButton1Click:Connect(function()m=not m UT()end)
local H=Instance.new("TextLabel")H.Size=UDim2.new(1,-24,0,12)H.Position=UDim2.new(0,12,0,288)H.BackgroundTransparency=1 H.Font=Enum.Font.GothamMedium H.Text="Shift: Hide | F4: Toggle | X: Close"H.TextColor3=Color3.fromRGB(80,80,80)H.TextSize=9 H.TextXAlignment=Enum.TextXAlignment.Center H.Parent=F
local CR=Instance.new("TextLabel")CR.Size=UDim2.new(1,-24,0,12)CR.Position=UDim2.new(0,12,0,300)CR.BackgroundTransparency=1 CR.Font=Enum.Font.GothamMedium CR.Text="Made by cloudvuacc"CR.TextColor3=Color3.fromRGB(60,60,80)CR.TextSize=9 CR.TextXAlignment=Enum.TextXAlignment.Center CR.Parent=F
local dr,ds,sp=false,Vector2.new(0,0),F.Position TB.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dr=true ds=i.Position sp=F.Position end end)g.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dr=false end end)g.InputChanged:Connect(function(i)if dr and i.UserInputType==Enum.UserInputType.MouseMovement then local d=i.Position-ds F.Position=UDim2.new(sp.X.Scale,sp.X.Offset+d.X,sp.Y.Scale,sp.Y.Offset+d.Y)end end)
spawn(function()while G and G.Parent do UV.Text="⏱️ "..x(tick()-l)task.wait(0.1)end end)
spawn(function()while G and G.Parent do if m then SD.BackgroundColor3=Color3.fromRGB(0,255*(math.sin(tick()*4)*0.4+0.6),0)end task.wait(0.05)end end)
spawn(function()while G and G.Parent do z()task.wait(math.random(25,45))end end)
e.CharacterAdded:Connect(function(C)local Hm=C:FindFirstChildOfClass("Humanoid")if Hm then Hm.Idled:Connect(function()if m then z()end end)end end)
if e.Character then local Hm=e.Character:FindFirstChildOfClass("Humanoid")if Hm then Hm.Idled:Connect(function()if m then z()end end)end end
g.InputBegan:Connect(function(i,gp)if not gp then if i.KeyCode==Enum.KeyCode.F4 then m=not m UT()elseif i.KeyCode==Enum.KeyCode.LeftShift or i.KeyCode==Enum.KeyCode.RightShift then F.Visible=not F.Visible end end end)
end

-- KEY GUI
local function D()local G=Instance.new("ScreenGui")G.Name="_q"G.ResetOnSpawn=false G.Parent=f
local F=Instance.new("Frame")F.Size=UDim2.new(0,360,0,210)F.Position=UDim2.new(0.5,-180,0.4,-105)F.BackgroundColor3=Color3.fromRGB(18,18,22)F.BorderSizePixel=0 F.Parent=G A(F,12)
local CX=Instance.new("TextButton")CX.Size=UDim2.new(0,26,0,26)CX.Position=UDim2.new(1,-32,0,6)CX.BackgroundColor3=Color3.fromRGB(220,40,40)CX.BorderSizePixel=0 CX.Font=Enum.Font.GothamBold CX.Text="✕"CX.TextColor3=Color3.fromRGB(255,255,255)CX.TextSize=13 CX.Parent=F A(CX,6)CX.MouseButton1Click:Connect(function()G:Destroy()end)
local Ti=Instance.new("TextLabel")Ti.Size=UDim2.new(1,0,0,24)Ti.Position=UDim2.new(0,0,0,10)Ti.BackgroundTransparency=1 Ti.Font=Enum.Font.GothamBold Ti.Text="🔑 ENTER KEY"Ti.TextColor3=Color3.fromRGB(0,255,150)Ti.TextSize=15 Ti.Parent=F
local UID=Instance.new("Frame")UID.Size=UDim2.new(1,-40,0,26)UID.Position=UDim2.new(0,20,0,38)UID.BackgroundColor3=Color3.fromRGB(12,12,16)UID.BorderSizePixel=0 UID.Parent=F A(UID,6)
local UIL=Instance.new("TextLabel")UIL.Size=UDim2.new(1,-55,1,0)UIL.Position=UDim2.new(0,8,0,0)UIL.BackgroundTransparency=1 UIL.Font=Enum.Font.GothamMedium UIL.Text="👤 ID: "..e.UserId UIL.TextColor3=Color3.fromRGB(180,180,255)UIL.TextSize=10 UIL.TextXAlignment=Enum.TextXAlignment.Left UIL.Parent=UID
local CpID=Instance.new("TextButton")CpID.Size=UDim2.new(0,45,0,16)CpID.Position=UDim2.new(1,-50,0,5)CpID.BackgroundColor3=Color3.fromRGB(80,80,100)CpID.BorderSizePixel=0 CpID.Font=Enum.Font.GothamMedium CpID.Text="COPY"CpID.TextColor3=Color3.fromRGB(255,255,255)CpID.TextSize=8 CpID.Parent=UID A(CpID,4)CpID.MouseButton1Click:Connect(function()pcall(function()setclipboard(tostring(e.UserId))end)St.Text="✅ ID copied!"St.TextColor3=Color3.fromRGB(0,255,0)end)
local GK=Instance.new("TextButton")GK.Size=UDim2.new(1,-40,0,32)GK.Position=UDim2.new(0,20,0,70)GK.BackgroundColor3=Color3.fromRGB(255,140,0)GK.BorderSizePixel=0 GK.Font=Enum.Font.GothamBold GK.Text="🔗 GET KEY"GK.TextColor3=Color3.fromRGB(255,255,255)GK.TextSize=12 GK.Parent=F A(GK,6)GK.MouseButton1Click:Connect(function()pcall(function()setclipboard(k)end)St.Text="✅ Link copied!"St.TextColor3=Color3.fromRGB(0,255,0)end)
local In=Instance.new("TextBox")In.Size=UDim2.new(1,-40,0,32)In.Position=UDim2.new(0,20,0,108)In.BackgroundColor3=Color3.fromRGB(10,10,14)In.BorderSizePixel=0 In.Font=Enum.Font.Code In.Text=""In.TextColor3=Color3.fromRGB(0,255,150)In.TextSize=12 In.Parent=F A(In,6)
local Sb=Instance.new("TextButton")Sb.Size=UDim2.new(1,-40,0,32)Sb.Position=UDim2.new(0,20,0,146)Sb.BackgroundColor3=Color3.fromRGB(0,180,100)Sb.BorderSizePixel=0 Sb.Font=Enum.Font.GothamBold Sb.Text="✅ SUBMIT"Sb.TextColor3=Color3.fromRGB(255,255,255)Sb.TextSize=13 Sb.Parent=F A(Sb,6)
local St=Instance.new("TextLabel")St.Size=UDim2.new(1,-40,0,18)St.Position=UDim2.new(0,20,0,182)St.BackgroundTransparency=1 St.Font=Enum.Font.GothamMedium St.Text="Copy ID → Website → Get key → Paste"St.TextColor3=Color3.fromRGB(150,150,150)St.TextSize=9 St.TextXAlignment=Enum.TextXAlignment.Center St.Parent=F
local CR2=Instance.new("TextLabel")CR2.Size=UDim2.new(1,-40,0,12)CR2.Position=UDim2.new(0,20,0,198)CR2.BackgroundTransparency=1 CR2.Font=Enum.Font.GothamMedium CR2.Text="Made by cloudvuacc"CR2.TextColor3=Color3.fromRGB(60,60,80)CR2.TextSize=8 CR2.TextXAlignment=Enum.TextXAlignment.Center CR2.Parent=F
local function PK(k)k=k:gsub("%s+",""):upper()if k==""then St.Text="❌ Enter key!"return end if u(k)then if not getgenv()._k or getgenv()._k==0 then p=os.time()w()end St.Text="✅ Valid!"task.wait(1)G:Destroy()B()else St.Text="❌ Invalid!"end end
Sb.MouseButton1Click:Connect(function()PK(In.Text)end)In.FocusLost:Connect(function(EP)if EP then PK(In.Text)end end)end
if o then B()else D()end
